# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build minified assets
          command: |
            echo "branch"
            if [ "$CIRCLE_BRANCH" == "master" ];
            then
              echo $CIRCLE_BRANCH -- master
            fi
            if [ "$CIRCLE_BRANCH" == "v4" ];
            then
              echo $CIRCLE_BRANCH -- v4
            fi
            echo $CIRCLE_BRANCH
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      #- run: yarn test
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Switch timezone to China
          command: sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone
      - run:
          name: Deploy Over SSH
          command: |
            echo "deploy"
            ssh root@101.132.64.76 "echo remote && date -R && cd /var/test && mkdir circle`date "+%Y%m%d-%R"`"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build